// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foo.proto

package example.dummy;

public final class FooOuterClass {
  private FooOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FooOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.dummy.Foo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>bool isOk = 3;</code>
     * @return The isOk.
     */
    boolean getIsOk();

    /**
     * <code>repeated string names_list = 4;</code>
     * @return A list containing the namesList.
     */
    java.util.List<java.lang.String>
        getNamesListList();
    /**
     * <code>repeated string names_list = 4;</code>
     * @return The count of namesList.
     */
    int getNamesListCount();
    /**
     * <code>repeated string names_list = 4;</code>
     * @param index The index of the element to return.
     * @return The namesList at the given index.
     */
    java.lang.String getNamesList(int index);
    /**
     * <code>repeated string names_list = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the namesList at the given index.
     */
    com.google.protobuf.ByteString
        getNamesListBytes(int index);
  }
  /**
   * Protobuf type {@code example.dummy.Foo}
   */
  public static final class Foo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.dummy.Foo)
      FooOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Foo.newBuilder() to construct.
    private Foo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Foo() {
      value_ = "";
      namesList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Foo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.dummy.FooOuterClass.internal_static_example_dummy_Foo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.dummy.FooOuterClass.internal_static_example_dummy_Foo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.dummy.FooOuterClass.Foo.class, example.dummy.FooOuterClass.Foo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISOK_FIELD_NUMBER = 3;
    private boolean isOk_ = false;
    /**
     * <code>bool isOk = 3;</code>
     * @return The isOk.
     */
    @java.lang.Override
    public boolean getIsOk() {
      return isOk_;
    }

    public static final int NAMES_LIST_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList namesList_;
    /**
     * <code>repeated string names_list = 4;</code>
     * @return A list containing the namesList.
     */
    public com.google.protobuf.ProtocolStringList
        getNamesListList() {
      return namesList_;
    }
    /**
     * <code>repeated string names_list = 4;</code>
     * @return The count of namesList.
     */
    public int getNamesListCount() {
      return namesList_.size();
    }
    /**
     * <code>repeated string names_list = 4;</code>
     * @param index The index of the element to return.
     * @return The namesList at the given index.
     */
    public java.lang.String getNamesList(int index) {
      return namesList_.get(index);
    }
    /**
     * <code>repeated string names_list = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the namesList at the given index.
     */
    public com.google.protobuf.ByteString
        getNamesListBytes(int index) {
      return namesList_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      if (isOk_ != false) {
        output.writeBool(3, isOk_);
      }
      for (int i = 0; i < namesList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, namesList_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      if (isOk_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isOk_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < namesList_.size(); i++) {
          dataSize += computeStringSizeNoTag(namesList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNamesListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof example.dummy.FooOuterClass.Foo)) {
        return super.equals(obj);
      }
      example.dummy.FooOuterClass.Foo other = (example.dummy.FooOuterClass.Foo) obj;

      if (getId()
          != other.getId()) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (getIsOk()
          != other.getIsOk()) return false;
      if (!getNamesListList()
          .equals(other.getNamesListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + ISOK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOk());
      if (getNamesListCount() > 0) {
        hash = (37 * hash) + NAMES_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getNamesListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static example.dummy.FooOuterClass.Foo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.dummy.FooOuterClass.Foo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.dummy.FooOuterClass.Foo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.dummy.FooOuterClass.Foo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.dummy.FooOuterClass.Foo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static example.dummy.FooOuterClass.Foo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static example.dummy.FooOuterClass.Foo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.dummy.FooOuterClass.Foo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.dummy.FooOuterClass.Foo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static example.dummy.FooOuterClass.Foo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static example.dummy.FooOuterClass.Foo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static example.dummy.FooOuterClass.Foo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(example.dummy.FooOuterClass.Foo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.dummy.Foo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.dummy.Foo)
        example.dummy.FooOuterClass.FooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return example.dummy.FooOuterClass.internal_static_example_dummy_Foo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return example.dummy.FooOuterClass.internal_static_example_dummy_Foo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                example.dummy.FooOuterClass.Foo.class, example.dummy.FooOuterClass.Foo.Builder.class);
      }

      // Construct using example.dummy.FooOuterClass.Foo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        value_ = "";
        isOk_ = false;
        namesList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return example.dummy.FooOuterClass.internal_static_example_dummy_Foo_descriptor;
      }

      @java.lang.Override
      public example.dummy.FooOuterClass.Foo getDefaultInstanceForType() {
        return example.dummy.FooOuterClass.Foo.getDefaultInstance();
      }

      @java.lang.Override
      public example.dummy.FooOuterClass.Foo build() {
        example.dummy.FooOuterClass.Foo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public example.dummy.FooOuterClass.Foo buildPartial() {
        example.dummy.FooOuterClass.Foo result = new example.dummy.FooOuterClass.Foo(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(example.dummy.FooOuterClass.Foo result) {
        if (((bitField0_ & 0x00000008) != 0)) {
          namesList_ = namesList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.namesList_ = namesList_;
      }

      private void buildPartial0(example.dummy.FooOuterClass.Foo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isOk_ = isOk_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof example.dummy.FooOuterClass.Foo) {
          return mergeFrom((example.dummy.FooOuterClass.Foo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(example.dummy.FooOuterClass.Foo other) {
        if (other == example.dummy.FooOuterClass.Foo.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getIsOk() != false) {
          setIsOk(other.getIsOk());
        }
        if (!other.namesList_.isEmpty()) {
          if (namesList_.isEmpty()) {
            namesList_ = other.namesList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureNamesListIsMutable();
            namesList_.addAll(other.namesList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                isOk_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureNamesListIsMutable();
                namesList_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>uint64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>uint64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean isOk_ ;
      /**
       * <code>bool isOk = 3;</code>
       * @return The isOk.
       */
      @java.lang.Override
      public boolean getIsOk() {
        return isOk_;
      }
      /**
       * <code>bool isOk = 3;</code>
       * @param value The isOk to set.
       * @return This builder for chaining.
       */
      public Builder setIsOk(boolean value) {
        
        isOk_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool isOk = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOk() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isOk_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList namesList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNamesListIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          namesList_ = new com.google.protobuf.LazyStringArrayList(namesList_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string names_list = 4;</code>
       * @return A list containing the namesList.
       */
      public com.google.protobuf.ProtocolStringList
          getNamesListList() {
        return namesList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string names_list = 4;</code>
       * @return The count of namesList.
       */
      public int getNamesListCount() {
        return namesList_.size();
      }
      /**
       * <code>repeated string names_list = 4;</code>
       * @param index The index of the element to return.
       * @return The namesList at the given index.
       */
      public java.lang.String getNamesList(int index) {
        return namesList_.get(index);
      }
      /**
       * <code>repeated string names_list = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the namesList at the given index.
       */
      public com.google.protobuf.ByteString
          getNamesListBytes(int index) {
        return namesList_.getByteString(index);
      }
      /**
       * <code>repeated string names_list = 4;</code>
       * @param index The index to set the value at.
       * @param value The namesList to set.
       * @return This builder for chaining.
       */
      public Builder setNamesList(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureNamesListIsMutable();
        namesList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names_list = 4;</code>
       * @param value The namesList to add.
       * @return This builder for chaining.
       */
      public Builder addNamesList(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureNamesListIsMutable();
        namesList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names_list = 4;</code>
       * @param values The namesList to add.
       * @return This builder for chaining.
       */
      public Builder addAllNamesList(
          java.lang.Iterable<java.lang.String> values) {
        ensureNamesListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, namesList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names_list = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamesList() {
        namesList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names_list = 4;</code>
       * @param value The bytes of the namesList to add.
       * @return This builder for chaining.
       */
      public Builder addNamesListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureNamesListIsMutable();
        namesList_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.dummy.Foo)
    }

    // @@protoc_insertion_point(class_scope:example.dummy.Foo)
    private static final example.dummy.FooOuterClass.Foo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new example.dummy.FooOuterClass.Foo();
    }

    public static example.dummy.FooOuterClass.Foo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Foo>
        PARSER = new com.google.protobuf.AbstractParser<Foo>() {
      @java.lang.Override
      public Foo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Foo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Foo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public example.dummy.FooOuterClass.Foo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_dummy_Foo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_dummy_Foo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tfoo.proto\022\rexample.dummy\"B\n\003Foo\022\n\n\002id\030" +
      "\001 \001(\004\022\r\n\005value\030\002 \001(\t\022\014\n\004isOk\030\003 \001(\010\022\022\n\nna" +
      "mes_list\030\004 \003(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_dummy_Foo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_dummy_Foo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_dummy_Foo_descriptor,
        new java.lang.String[] { "Id", "Value", "IsOk", "NamesList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
